socialapp/groups/urls.py
from django.urls import path

from . import views

app_name = "groups"

urlpatterns = [
    path('', views.GroupListView.as_view(), name="group_list"),
    path('group/<slug:group_slug>/', views.GroupDetailView.as_view(), name="group_detail"),
    path('group/<slug:group_slug>/posts/', views.GroupPostsListView.as_view(), name="group_posts"),
    path('group/<slug:group_slug>/post/<slug:post_slug>/', views.GroupPostDetailView.as_view(), name="post_detail"),
    path('group/<slug:group_slug>/post/<slug:post_slug>/edit/', views.GroupPostUpdateView.as_view(), name="update_post"),
    path("search_group/", views.search_post, name="search_group"),
    
    path('user_list/<slug:group_slug>/', views.UsersListView.as_view(), name="user_list"),
    
    
    
    path('create_group/', views.GroupCreateView.as_view(), name="create_group"),
    path('create_post/', views.add_post, name="add_post"),
    path('group/<slug:group_slug>/create_post/', views.GroupPostCreateView.as_view(), name="add_post_in_group"),
    path('group/<slug:group_slug>/post/<slug:post_slug>/delete/', views.delete_post, name="delete_post"),
    
    
    path("group/<slug:group_slug>/post/<slug:post_slug>/comment/", views.CommentManagerView.as_view(), name="add_comment"),
    path("group/<slug:group_slug>/post/<slug:post_slug>/comment/<int:comment_id>/delete", views.CommentManagerView.as_view(), name="delete_comment"),
    path('group/<slug:group_slug>/post/<slug:post_slug>/comment/<int:comment_id>/edit/', views.CommentUpdateView.as_view(), name="comment_update"),
    path("group/<slug:group_slug>/post/<slug:post_slug>/like/", views.like_post, name="like_post"),
    
    path('group/<slug:group_slug>/follow/', views.follow_to_group, name="follow"),
    path('group/<slug:group_slug>/add_user/<str:username>/', views.add_user_to_group, name="add_user"),
]

socialapp/posts/urls.py
from django.urls import path

from . import views


# app_name = 'posts'


urlpatterns = [
    path('', views.PostListView.as_view(), name="home"),
    path('post/<slug:post_slug>/', views.PostDetailView.as_view(), name="post_detail"),
    path("category/<slug:cat_slug>/", views.PostCategoryListView.as_view(), name="category_detail"),
    path("tag/<slug:tag_slug>/", views.PostTagsListView.as_view(), name="tag_detail"),
    path("add_post/", views.PostCreateView.as_view(), name="add_post"),
    path('edit/<slug:slug>/', views.PostUpdateView.as_view(), name="update_post"),
    path("post/<slug:post_slug>/comment/", views.AddCommentView.as_view(), name="add_comment"),
    path("comment/<int:comment_id>/delete/", views.AddCommentView.as_view(), name="comment_delete"),
    path('post/<slug:post_slug>/comment/<int:comment_id>/edit/', views.CommentUpdateView.as_view(), name="edit_comment"),
    path("recomendation/", views.RecomendationListView.as_view(), name="recomendations"),
    path("search_post/", views.search_posts, name="search_post"),
    path("post/<slug:post_slug>/like/", views.like_post, name="like_post"),
    
    path('notifications/', views.NotificationListView.as_view(), name="notifications_list"),
    path('read/<int:notification_id>/', views.mark_notification_as_read, name="mark_notification_as_read"),
    path("about/", views.about, name='about'),
    path("contact/", views.contact, name="contact"),
]

socialapp/socialapp/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include

from socialapp import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls')),
    path('users/', include("users.urls", namespace="users")),
    path("groups/", include("groups.urls", namespace="groups")),
    path("__debug__/", include("debug_toolbar.urls")),
    
    path('api/', include('posts.api.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    
    

socialapp/users/urls.py
from django.urls import path

from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path('registration/', views.RegisterUser.as_view(), name="registration"),
    path("profile/", views.ProfileUserView.as_view(), name="profile"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    
    path("profile/<str:username>/", views.UserProfileView.as_view(), name="user_profile"),
    path('subscribe/<str:username>/', views.subscribe, name='subscribe'),
    path('unsubscribe/<str:username>/', views.unsubscribe, name='unsubscribe'),
    
    path("subscribers/<str:username>/", views.UserSubscribersView.as_view(), name="subscribers_list"),
    path("subscriptions/<str:username>/", views.UserSubscriptionsView.as_view(), name="subscriptions_list"),
    
    path("my_posts/", views.MyPostListView.as_view(), name="my_posts"),
    path("favorite_posts/", views.FavoriteListView.as_view(), name="favorite_posts"),
    path("my_comments/", views.CommentsListView.as_view(), name="my_comments"),
]

socialapp/groups/forms.py
from django import forms
from .models import GroupComment, Group, GroupPost, GroupMembership
from django.db.models import Q

class CommentCreateForm(forms.ModelForm):
    
    class Meta:
        model = GroupComment
        fields = ['content']
        
        
    def clean_content(self):
        content = self.cleaned_data['content']
        if len(content) > 300:
            raise forms.ValidationError("Комментарий не может превышать 300 символов")
        return content
    
class GroupCreateForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = ['name', 'description', 'cover_image', 'privacy']
        widgets = {
            'name': forms.TextInput(attrs={"placeholder": "Заголовок"}),
            'description': forms.Textarea(attrs={"placeholder": "Описание"}),
        }
        
    def clean_name(self):
        name = self.cleaned_data['name']
        if len(name) > 30:
            raise forms.ValidationError("Заголовок не может превышать 30 символов")
        return name
    
class GroupPostWithGroupForm(forms.ModelForm):
    class Meta:
        model = GroupPost
        fields = ['group', 'title', 'content', 'photo', 'tags']
        widgets = {
            'title': forms.TextInput(attrs={"placeholder": "Заголовок"}),
            'content': forms.Textarea(attrs={"placeholder": "Контент"}),
        }
    
    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)
        if user:
            self.fields['group'].queryset = Group.objects.filter(
                Q(memberships__user=user) | Q(owner=user)
            ).distinct()
            self.fields['group'].empty_label="Выберите группу"
        
class GroupPostForm(forms.ModelForm):
    class Meta:
        model = GroupPost
        fields = ['title', 'content', 'photo', 'tags']
        widgets = {
            'title': forms.TextInput(attrs={"placeholder": "Заголовок"}),
            'content': forms.Textarea(attrs={"placeholder": "Контент"})
        }

socialapp/groups/views.py
from typing import Any
from django.db.models.base import Model as Model
from django.db.models.query import QuerySet
from django.shortcuts import render, get_object_or_404
from .models import Group, GroupMembership, GroupPost, GroupComment
from django.views.generic import ListView, DetailView, UpdateView, CreateView, DeleteView, View
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, HttpResponseRedirect
from django.db.models import Q
from django.urls import reverse_lazy

from posts.utils import DataMixin
from groups.forms import CommentCreateForm, GroupCreateForm, GroupPostWithGroupForm, GroupPostForm


class GroupListView(LoginRequiredMixin, DataMixin, ListView):
    model = Group
    template_name = "groups/group_list.html"
    context_object_name = "groups"
    title_page = "Группы"
    paginate_by = 12
    
    def get_queryset(self) -> QuerySet[Any]:
        return Group.objects.filter(privacy=Group.Status.OPEN).select_related("owner")
    
    
class GroupDetailView(LoginRequiredMixin, DataMixin, DetailView):
    model = Group
    template_name = "groups/group_detail.html"
    context_object_name = "group"
    slug_url_kwarg = "group_slug"
    
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        group = self.get_object()
        context['members'] = GroupMembership.objects.filter(group=group)
        context['has_posts'] = GroupPost.objects.filter(group=group).exists()
        context["user_is_member"] = group.memberships.filter(user=self.request.user).exists()
        return self.get_mixin_context(context, title="Группа - " + group.name)
    
    def get_object(self, queryset: QuerySet[Any] | None = ...) -> Model:
        return Group.objects.get(slug=self.kwargs[self.slug_url_kwarg], privacy=Group.Status.OPEN)
    

class GroupPostsListView(LoginRequiredMixin, DataMixin, ListView):
    model = GroupPost
    template_name = "groups/group_posts_list.html"
    context_object_name = "posts"
    paginate_by = 10
    
    def get_queryset(self) -> QuerySet[Any]:
        self.group = get_object_or_404(Group, slug=self.kwargs["group_slug"])
        return GroupPost.objects.filter(group=self.group).select_related("author")
    
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context["group"] = Group.objects.get(slug=self.kwargs["group_slug"])
        context["user_is_member"] = context["group"].memberships.filter(user=self.request.user).exists()
        return self.get_mixin_context(context, title="Посты группы " + context['group'].name)
    
    
class GroupPostDetailView(LoginRequiredMixin, DataMixin, DetailView):
    model = GroupPost
    template_name = "groups/post_detail.html"
    context_object_name = "post"
    slug_url_kwarg = "post_slug"
    
    def get_object(self, queryset: QuerySet[Any] | None = ...) -> Model:
        self.group = get_object_or_404(Group, slug=self.kwargs["group_slug"])
        return get_object_or_404(GroupPost, group=self.group, slug=self.kwargs[self.slug_url_kwarg])
    
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['group'] = get_object_or_404(Group, slug=self.kwargs["group_slug"])
        post = context['post']
        context['liked'] = False
        if self.request.user.is_authenticated:
            context['liked'] = post.likes.filter(id=self.request.user.id).exists()
        return self.get_mixin_context(context, title='Пост ' + context["post"].title, form=CommentCreateForm())
    
class GroupPostUpdateView(LoginRequiredMixin, DataMixin, UpdateView):
    model = GroupPost
    form_class = GroupPostForm
    template_name = "groups/group_post_create.html"
    slug_url_kwarg = "post_slug"
    
    def get_success_url(self) -> str:
        group_slug = self.kwargs['group_slug']
        return reverse_lazy("groups:group_posts", kwargs={'group_slug': group_slug})

# class GroupPostDeleteView(LoginRequiredMixin, DeleteView):
#     model = GroupPost
#     template_name = "groups/post_detail.html"
#     success_url = reverse_lazy("home")
#     slug_url_kwarg = "post_slug"
    
#     def get_object(self, queryset: QuerySet[Any] | None = ...) -> Model:
#         return get_object_or_404(GroupPost, slug=self.slug_url_kwarg, group__slug=self.kwargs['group_slug'])
    
    
#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context['group_slug'] = self.kwargs.get('group_slug')
#         return context

    
@login_required
def delete_post(request, group_slug, post_slug):
    group = get_object_or_404(Group, slug=group_slug, privacy=Group.Status.OPEN)
    post = get_object_or_404(GroupPost, slug=post_slug, group=group)
    post.delete()
    return redirect("groups:group_posts", group_slug)    

class GroupCreateView(LoginRequiredMixin, DataMixin, CreateView):
    form_class = GroupCreateForm
    template_name = "groups/group_create.html"
    title_page = "Создание группы"
    
    
    def form_valid(self, form):
        group = form.save(commit=False)
        group.owner = self.request.user
        group = form.save()
        return super().form_valid(form)
    
    
class GroupPostCreateView(LoginRequiredMixin, DataMixin, CreateView):
    form_class = GroupPostForm
    template_name = "groups/group_post_create.html"
    
    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.group = get_object_or_404(Group, slug=self.kwargs["group_slug"])
        return super().form_valid(form)
    
    def get_success_url(self) -> str:
        group_slug = self.kwargs["group_slug"]
        post_slug = self.object.slug
        return reverse_lazy("groups:post_detail", kwargs={'group_slug': group_slug, 'post_slug': post_slug})
    

@login_required
def add_post(request):
    if request.method == "POST":
        form = GroupPostWithGroupForm(request.POST, request.FILES, user=request.user)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.owner = request.user  # Назначаем владельцем поста текущего пользователя
            post.save()
            form.save_m2m()
            return redirect("groups:group_posts", group_slug=post.group.slug)
        else:
            print(form.errors)  # Отладочное сообщение
    else:
        form = GroupPostWithGroupForm(user=request.user)
    return render(request, 'groups/group_post_create.html', {"form": form})

class CommentManagerView(LoginRequiredMixin, View):

    def dispatch(self, request, *args, **kwargs):
        if request.method == "POST" and request.POST.get("_method") == "DELETE":
            request.method = "DELETE"
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, group_slug, post_slug, comment_id=None):
        group = get_object_or_404(Group, slug=group_slug)
        post = get_object_or_404(GroupPost, slug=post_slug, group=group)
        if comment_id:
            comment = get_object_or_404(GroupComment, id=comment_id, post=post)
            form = CommentCreateForm(request.POST, instance=comment)
        else:
            form = CommentCreateForm(request.POST)
        
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.post = post
            new_comment.user = request.user
            parent_id = request.POST.get('parent_id')
            if parent_id:
                new_comment.parent = GroupComment.objects.get(id=parent_id)
            
            new_comment.save()
            return redirect("groups:post_detail", group_slug=group_slug, post_slug=post_slug)
        
        return render(request, "groups/post_detail.html", {"group": group, "post": post, "form": form})

    def delete(self, request, group_slug, post_slug, comment_id):
        comment = get_object_or_404(GroupComment, id=comment_id)
        if request.user == comment.user:
            comment.delete()
        return redirect('groups:post_detail', group_slug=group_slug, post_slug=post_slug)


class CommentUpdateView(LoginRequiredMixin, UpdateView):
    model = GroupComment
    fields = ['content']
    template_name = "groups/comment_edit.html"
    pk_url_kwarg = "comment_id"
    
    def get_success_url(self) -> str:
        post_slug = self.object.post.slug
        group_slug = self.object.post.group.slug
        return reverse_lazy("groups:post_detail", kwargs={"post_slug": post_slug,
                                                   "group_slug": group_slug})

class UsersListView(LoginRequiredMixin, DataMixin, ListView):
    model = get_user_model()
    template_name = "groups/user_list.html"
    context_object_name = "users"
    title_page = "Выберете пользователя"
    
    def get_queryset(self) -> QuerySet[Any]:
        current_user = self.request.user
        subscriptions = current_user.subscriptions.all()
        others = get_user_model().objects.exclude(id__in=subscriptions).exclude(id=current_user.id)
        
        queryset = list(subscriptions) + list(others)
        return queryset
    
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        current_user = self.request.user
        users = get_user_model().objects.all()
        context['group'] = get_object_or_404(Group, slug=self.kwargs["group_slug"])
        context['subscriptions'] = current_user.subscriptions.all()
        context['user_in_group'] = context["group"].memberships.filter(user=current_user).exists()
        context['user_membership_info'] = [
        (user, GroupMembership.objects.filter(group=context['group'], user=user).exists())
        for user in users
    ]

socialapp/groups/templates/groups/comment_edit.html
{% extends "base.html" %}

{% block css %}{% endblock css %}



{% block content %}

<form method="post">
    <h1>Редактировать комментарий</h1>
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Сохранить</button>
</form>
{% endblock content %}



{% block sidebar %}{% endblock sidebar %}

socialapp/groups/templates/groups/group_create.html
{% extends "base.html" %}
{% load static %}


{% block css %}
<link rel="stylesheet" href="{% static "groups/css/group_create.css" %}">
{% endblock css %}

{% block content %}
<form method="post" enctype="multipart/form-data">
    <h1>Создать новую группу</h1>
    {% csrf_token %}
    <input type="hidden" name="next" value="{{ next }}"></input>
    {% for f in form %}
    <div class="form-group">
        {{ f }}
        <div class="form-error">{{ f.errors }}</div>
    </div>
    {% endfor %}            
    <button type="submit" class="btn">Создать группу</button>
</form>
{% endblock content %}


{% block sidebar %}{% endblock sidebar %}

socialapp/groups/templates/groups/group_detail.html
{% extends "base.html" %}
{% load static %}



{% block css %}
<link rel="stylesheet" href="{% static "groups/css/group_detail.css" %}">
{% endblock css %}



{% block content %}
<div class="container">
    <div class="group-header">
        <img src="{{ group.cover_image.url }}" alt="{{ group.name }}" class="group-image">
        <div class="group-details">
            <h1 class="group-title">{{ group.name }}</h1>
            <p class="group-info"><strong>Админ:</strong> {{ group.owner.username }}</p>
            <p class="group-info"><strong>Дата:</strong> {{ group.created_at|date:"Y-m-d" }}</p>
            {% comment %} {% if request.user == group.owner %}
            <a href="{% url "groups:user_list" group.slug %}" class="create-btn">Добавить пользователя</a>
            {% endif %} {% endcomment %}
            {% if request.user == group.owner or user_is_member %}
            <a href="{% url "groups:add_post_in_group" group.slug %}" class="create-btn">Добавить пост</a>
            <a href="{% url "groups:user_list" group.slug %}" class="create-btn">Добавить пользователя</a>
            {% else %}
            <a href="{% url "groups:follow" group.slug %}" class="create-btn">Присоединится к группе</a>
            {% endif %}
        </div>
    </div>
    <div class="group-description">
        <p>{{ group.description }}</p>
    </div>
    <div class="group-members">
        {% if members %}
        <h2>Members</h2>
        <ul class="member-list">
            {% for member in members %}
            <li class="member-item"><a href="{% url "users:user_profile" member.user.username %}">{{ member.user.username }}</a></li>
            {% endfor %}
        </ul>
        {% else %}
        <h2>Здесь пока никого нету</h2>
        {% endif %}
    </div>
    {% if has_posts %}
    <a href="{% url 'groups:group_posts' group.slug %}" class="group-posts-link">View Posts</a>
    {% else %}
    {% if request.user == group.owner %}
    <a href="{% url "groups:add_post_in_group" group.slug %}">Добавить пост</a>
    {% else %}
    <p>На данный момент в этой группе постов нету</p>
    {% endif %}
    {% endif %}
    
</div>
{% endblock content %}



{% block sidebar %}{% endblock sidebar %}

socialapp/groups/templates/groups/group_list.html
{% extends "base.html" %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static "groups/css/group_list.css" %}">
{% endblock css %}


{% block content %}
<div class="container">
    <div class="search-block">
        <form method="get" class="search-form" action="{% url "groups:search_group" %}">
            <input type="text" name="query" placeholder="Поиск" class="input-group">
            <button class="search-btn" type="submit">Поиск</button>
        </form>
    </div>
    <ul class="opciones">
        <li><a href="{% url "groups:create_group" %}">Создать новую группу</a></li>
        <li><a href="{% url "groups:add_post" %}">Создать пост</a></li>
    </ul>

    {% if groups %}
    <h1>Доступные группы</h1>
    <div class="groups-list">
        {% for group in groups %}
        <div class="group-card">
            <img src="{{ group.cover_image.url }}" alt="{{ group.name }}" class="group-image">
            <div class="group-content">
                <h2 class="group-title">{{ group.name }}</h2>
                <p class="group-info"><strong>Админ:</strong> {{ group.owner.username }}</p>
                <p class="group-info"><strong>Дата:</strong> {{ group.created_at|date:"Y-m-d" }}</p>
                <p class="group-description">{{ group.description|truncatewords:20 }}</p>
                <a href="{% url "groups:group_detail" group.slug %}" class="group-view-button">Посмотреть</a>
            </div>
        </div>
        {% endfor %}
    </div>
    {% else %}
    <h1>Здесь пока ничего нету</h1>
    {% endif %}
    {% include "groups/include/pagination.html" with groups=page_obj %}
</div>
{% endblock content %}


{% block sidebar %}
{% comment %} <aside class="sidebar">
    <ul class="opciones">
        <li><a href="{% url "groups:create_group" %}">Создать новую группу</a></li>
        <li><a href="{% url "groups:add_post" %}">Создать пост</a></li>
    </ul>
</aside> {% endcomment %}
{% endblock sidebar %}

socialapp/groups/templates/groups/group_post_create.html
{% extends "base.html" %}
{% load static %}


{% block css %}
<link rel="stylesheet" href="{% static "groups/css/group_create.css" %}">
{% endblock css %}

{% block content %}
<form method="post" enctype="multipart/form-data">
    <h1>Создать новый пост</h1>
    {% csrf_token %}
    <input type="hidden" name="next" value="{{ next }}"></input>
    {% for f in form %}
    <div class="form-group">
        {{ f }}
        <div class="form-error">{{ f.errors }}</div>
    </div>
    {% endfor %}            
    <button type="submit" class="btn">Создать пост</button>
</form>
{% endblock content %}



{% block sidebar %}{% endblock sidebar %}

socialapp/groups/templates/groups/post_detail.html
{% extends "base.html" %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static "groups/css/post_detail.css" %}">
{% endblock css %}

{% block content %}
<a class="back-btn" href="{% url "groups:group_posts" group.slug %}">Вернуться назад</a>
<div class="post-container">
    
    <div class="post-header">
        {% if post.author.photo %}
        <img src="{{ post.author.photo.url }}" alt="Фото {{ post.author.username }}">
        {% else %}
        <img src="{{ default_img }}" alt="Фото {{ post.author.username }}">
        {% endif %}
        
        <div class="author-info">
            <a href="{% url "users:user_profile" post.author.username %}"><h2>{{ post.author.username }}</h2></a>
            <p>{{ post.time_create }}</p>
        </div>
        
        <p>Лайки: {{ post.total_likes }}</p>
        {% if user.is_authenticated %}
        <form action="{% url 'groups:like_post' group.slug post.slug %}" method="POST">
        {% csrf_token %}
        {% if liked %}
            <button class="dislike-btn" type="submit" name="post_id" value="{{ post.id }}">Убрать лайк</button>
        {% else %}
            <button class="like-btn" type="submit" name="post_id" value="{{ post.id }}">Поставить</button>
        {% endif %}
        </form>
        {% else %}
            <p><a href="{% url 'users:login' %}?next={{ request.path }}">Log in to like this post.</a></p>
        {% endif %}
    </div>
    
    <h1>{{ post.title }}</h1>
    <img class="post-img" src="{{ post.photo.url }}" alt="Изображение поста">
    
    <div class="post-content">
        <p>{{ post.content }}</p>
    </div>

    <div class="tags-section">
        <h2>Теги</h2>
        {% for tag in post.tags.all %}
            <a href="{% url 'tag_detail' tag.slug %}" class="tag">{{ tag.tag }}</a>
        {% endfor %}
    </div>

    {% if request.user == post.author or request.user == group.owner %}
    <div class="btns">
        <a href="{% url "groups:update_post" group.slug post.slug %}" class="edit-btn">Редактировать</a>
        <a href="{% url "groups:delete_post" group.slug post.slug %}" class="delete-btn">Удалить</a>
    </div>
    {% endif %}
    
    <hr>
    
    <div class="comments-section">
        <h2>Комментарии</h2>
        
        <!-- Форма для добавления комментариев -->
        <form id="comment-form" method="post" action="{% url "groups:add_comment" group.slug post.slug  %}">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="hidden" name="parent_id" id="parent_id">
            <button type="submit">Добавить комментарий</button>
        </form>
        
        <hr>
        
        <!-- Список комментариев -->
        <div id="comments-list">
            {% for comment in post.group_comments.all %}
                <div class="comment">
                    <strong>{{ comment.user.username }}</strong>
                    <p>{{ comment.content|linebreaksbr }}</p>
                    <!-- Кнопка "Ответить" -->
                    <a href="#" class="reply-link" data-comment-id="{{ comment.id }}">Ответить</a>
                    {% if request.user == comment.user %}
                    <form method="post" action="{% url 'groups:delete_comment' group.slug post.slug comment.id %}" style="display:inline;">
                        {% csrf_token %}
                        <input type="hidden" name="_method" value="DELETE">
                        <button type="submit">Удалить</button>
                    </form>
                    <a href="{% url "groups:comment_update" group.slug post.slug comment.id %}">Редактировать</a>
                    {% endif %}

                    <!-- Форма для ответа на комментарий -->
                    <form class="reply-form" id="reply-form-{{ comment.id }}" method="post" action="{% url 'groups:add_comment' group.slug post.slug %}">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <input type="hidden" name="parent_id" value="{{ comment.id }}">
                        <button type="submit">Ответить на комментарий</button>
                    </form>

                    <!-- Вложенные комментарии -->
                    {% for reply in comment.replies.all %}
                        <div class="reply">
                            <strong>{{ reply.user.username }}</strong>
                            <p>{{ reply.content }}</p>
                        </div>
                    {% endfor %}
                </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock content %}

{% block sidebar %}{% endblock sidebar %}


{% block js %}
<script>
    document.addEventListener("DOMContentLoaded", function() {
        var replyLinks = document.querySelectorAll('.reply-link');

        replyLinks.forEach(function(link) {
            link.addEventListener('click', function(event) {
                event.preventDefault();
                var commentId = this.getAttribute('data-comment-id');
                // Скрыть все формы для ответов
                var replyForms = document.querySelectorAll('.reply-form');
                replyForms.forEach(function(form) {
                    form.style.display = 'none';
                });
                // Показать форму для текущего комментария
                var replyForm = document.getElementById('reply-form-' + commentId);
                replyForm.style.display = 'block';
            });
        });
    });
</script>
{% endblock js %}

socialapp/groups/templates/groups/user_list.html
{% extends "base.html" %}
{% load static %}


{% block css %}
<link rel="stylesheet" href="{% static "groups/css/user_list.css" %}">
{% endblock css %}


{% block content %}


<div class="container">
    {% if request.user == group.owner %}
    <ul class="users-list">
        {% for user, is_member in user_membership_info %}
            <li class="user-item">
                <div class="user-info">
                    {% if user.photo %}
                        <img src="{{ user.photo.url }}" alt="{{ user.username }}" class="user-photo">
                    {% else %}
                        <img src="{{ default_img }}" alt="{{ user.username }}" class="user-photo">
                    {% endif %}
                    <a href="{% url 'users:user_profile' user.username %}">{{ user.username }}</a>
                </div>
                <div class="user-actions">
                    {% if user in subscriptions %}
                        <a href="{% url 'users:unsubscribe' user.username %}" class="subs-btn">Отписаться</a>                
                    {% else %}
                        <a id="unsubscribe" href="{% url 'users:subscribe' user.username %}" class="subs-btn">Подписаться</a>
                    {% endif %}

                    {% if request.user == group.owner %}
                        {% if is_member %}
                            {% comment %} <p class="subs-btn">Пользователь уже в группе</p> {% endcomment %}
                        {% else %}
                            <a id="subscribe" href="{% url 'groups:add_user' group.slug user.username %}" class="subs-btn">Добавить</a>
                        {% endif %}
                    {% endif %}
                </div>
            </li>
        {% endfor %}
    </ul>
    {% else %}
        Сначала присоеденись в группу, чтобы была возможность добавлять и удалять пользователей
        <a href="{% url 'groups:follow' group.slug %}">Присоединится к группе</a>
    {% endif %}
</div>


{% endblock content %}


{% block sidebar %}{% endblock sidebar %}